name: build-test
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Run coverage
        run: |
          set -e
          echo "" > coverage.txt
          for d in $(go list ./... | grep -v vendor); do
            go test -race -coverprofile=profile.out -covermode=atomic $d
            if [ -f profile.out ]; then
              cat profile.out >> coverage.txt
              rm profile.out
            fi
          done

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
